### ISSUE TITLE
[Backlog 6] Identify all relevant tables on transtats website

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAPCrawler#3]

**Comment by o4ier** [comment]
T-100 International Market (All Carriers) - http://transtats.bts.gov/Fields.asp?Table_ID=260 (Flüge mit Umstiegen)
T-100 International Segment (All Carriers) - http://transtats.bts.gov/Fields.asp?Table_ID=261 (Non-stop Flüge)

Es gibt keine Tabelle, welche Delays von internationalen Flügen abbildet. Nur für domestic flights werden diese erfasst (http://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236&DB_Short_Name=On-Time). Cancellation data ist aber für internationale Flüge in den beiden oberen Tabellen enthalten.

Needed Lookup-Tables:
Dest/OriginCountry - http://transtats.bts.gov/Download_Lookup.asp?Lookup=L_COUNTRY_CODE
Dest/OriginCityMarketID - http://transtats.bts.gov/Download_Lookup.asp?Lookup=L_CITY_MARKET_ID
AirlineID - http://transtats.bts.gov/Download_Lookup.asp?Lookup=L_AIRLINE_ID

**Comment by o4ier** [comment]
Change of requirements on 20160421 from Flights US<>Germany to New York > other US Cities (Continental, Alaska, Hawaii)

**Comment by o4ier** [comment]
T-100 Domestic Segment (All Carriers)
http://transtats.bts.gov/DL_SelectFields.asp?Table_ID=311
DepScheduled
DepPerformed
Passengers
AirlineID
OriginCityMarketID
DestCityMarketID
Month

On-Time Performance
http://transtats.bts.gov/DL_SelectFields.asp?Table_ID=236
Year
Month
DayOfWeek
FlightDate
AirlineID
OriginCityMarketID
DestCityMarketID
DepDelayMinutes 
ArrDelayMinutes 
Cancelled

Needed Lookup-Tables:
Dest/OriginCityMarketID - http://transtats.bts.gov/Download_Lookup.asp?Lookup=L_CITY_MARKET_ID
AirlineID - http://transtats.bts.gov/Download_Lookup.asp?Lookup=L_AIRLINE_ID
