### ISSUE TITLE
Restructure code

### ISSUE THREAD

**Issue by o4ier** [ORFAP/FAPCrawler#9]
split into 3 parts:
one method for actual crawling
one method for parsing
one method for sending to backend

-> testing made possible

**Comment by Arne2** [comment]
If i have two methods for crawling and sending to backend, i have to save all data during crawling, so i can send it to the backend later. Is this useful?

**Comment by darenegade** [comment]
There is no need to save all data. 
The input of the crawling is the transtats website and the output is the .csv table. 
The input of the parse method is the . csv table and the output are the entities. 
The sending to back-end method takes the entities and sends them to the backend. 
U can build a work chain to achieve the whole data crawling and in addition to that u can test the methods by its own. Especially the parse method in an unit test without internet and back-end access.
